name: Scrape Data

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 1 * * *' # runs at 1 AM every day

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Add FlareSolverr as a service
    services:
      flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:latest
        ports:
          - 8191:8191
        options: --name flaresolverr
    
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # Updated to v3

      - name: setup python
        uses: actions/setup-python@v4 # Updated to v4
        with:
          python-version: '3.11.3'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for FlareSolverr to start
        run: |
          echo "Waiting for FlareSolverr to initialize..."
          sleep 15
          # Test if FlareSolverr is responding
          curl -s http://localhost:8191/v1 || echo "FlareSolverr might not be ready yet"

      - name: execute py script
        run: python main.py

      - name: commit files
        run: |
          git config --local user.email "24556317+Johnnycyan@users.noreply.github.com"
          git config --local user.name "Johnnycyan"
          git add -A
          git diff --staged --quiet || git commit -m "Update Data"

      - name: push changes
        uses: ad-m/github-push-action@v0.8.0 # Updated version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Use built-in token
          branch: master
